AWSTemplateFormatVersion: 2010-09-09
Description: Stack for testing PatchBaseline resource.
Resources:
  TestPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: CanaryTestPatchBaseline
      Description: Baseline containing updates approved for AMAZON_LINUX instances
      OperatingSystem: AMAZON_LINUX
      PatchGroups:
        - CanaryTestPatchGroup
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              PatchFilters:
                - Values:
                    - Security
                    - Bugfix
                  Key: CLASSIFICATION
            ApproveAfterDays: 7
            ComplianceLevel: HIGH
            EnableNonSecurity: true
          - PatchFilterGroup:
              PatchFilters:
                - Values:
                    - "*"
                  Key: CLASSIFICATION
            ApproveAfterDays: 7
            ComplianceLevel: CRITICAL
            EnableNonSecurity: true
      Tags:
        - Value: CanaryTestKey
          Key: CanaryTestValue