version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
      python: 3.9
    commands:
      - pip install --upgrade 'six==1.15.0'
      - pip install pre-commit
  build:
    commands:
      # pre-build check for commit hooks
      - pre-commit run --all-files
      # install aws-cloudformation-rpdk
      - pip install cloudformation-cli cloudformation-cli-java-plugin
      # end-to-end test child repo for aws-ssm-association(s)
      - cd "$CODEBUILD_SRC_DIR"
      - cd aws-ssm-association
      - mvn clean verify --no-transfer-progress
      # end-to-end test child repo for aws-ssm-parameter(s)
      - cd "$CODEBUILD_SRC_DIR"
      - cd aws-ssm-parameter
      - mvn clean verify --no-transfer-progress
      # end-to-end test child repo for aws-ssm-maintenancewindow(s)
      - cd "$CODEBUILD_SRC_DIR"
      - cd aws-ssm-maintenancewindow
      - mvn clean verify --no-transfer-progress
      # end-to-end test child repo for aws-ssm-maintenancewindowtask(s)
      - cd "$CODEBUILD_SRC_DIR"
      - cd aws-ssm-maintenancewindowtask
      - mvn clean verify --no-transfer-progress
      # end-to-end test child repo for aws-ssm-maintenancewindowtarget(s)
      - cd "$CODEBUILD_SRC_DIR"
      - cd aws-ssm-maintenancewindowtarget
      - mvn clean verify --no-transfer-progress
      # end-to-end test child repo for aws-ssm-opsmetadata(s)
      - cd "$CODEBUILD_SRC_DIR"
      - cd aws-ssm-opsmetadata
      - mvn clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-ssm-association/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-ssm-parameter/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-ssm-maintenancewindow/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-ssm-maintenancewindowtask/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-ssm-maintenancewindowtarget/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-ssm-opsmetadata/rpdk.log"
