package com.amazonaws.ssm.document;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.MapUtils;
import org.apache.commons.lang3.StringUtils;
import software.amazon.awssdk.services.ssm.model.AttachmentsSource;
import software.amazon.awssdk.services.ssm.model.CreateDocumentRequest;
import software.amazon.awssdk.services.ssm.model.DocumentRequires;
import software.amazon.awssdk.services.ssm.model.GetDocumentRequest;
import software.amazon.awssdk.services.ssm.model.Tag;

import lombok.NonNull;
import software.amazon.cloudformation.resource.IdentifierUtils;

import javax.annotation.Nullable;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Translates CloudFormation's resource model to AWS resource model.
 */
class DocumentModelTranslator {
    private static final String DEFAULT_DOCUMENT_NAME_PREFIX = "document";
    private static final String EMPTY_STACK_NAME = "";
    private static final int DOCUMENT_NAME_MAX_LENGTH = 128;
    private static final String DOCUMENT_NAME_DELIMITER = "-";

    /**
     * Generate CreateDocumentRequest from the CreateResource request.
     */
    CreateDocumentRequest generateCreateDocumentRequest(@NonNull final ResourceModel model,
                                                        @Nullable final Map<String, String> systemTags,
                                                        @NonNull final String requestToken) {
        final String documentName;

        if (StringUtils.isEmpty(model.getName())) {
            documentName = generateName(systemTags, requestToken);
        } else {
            documentName = model.getName();
        }

        return CreateDocumentRequest.builder()
                .name(documentName)
                .versionName(model.getVersionName())
                .content(model.getContent())
                .documentFormat(model.getDocumentFormat())
                .documentType(model.getDocumentType())
                .targetType(model.getTargetType())
                .tags(translateTags(model.getTags()))
                .attachments(translateAttachments(model.getAttachments()))
                .requires(translateRequires(model.getRequires()))
                .build();
    }

    GetDocumentRequest generateGetDocumentRequest(@NonNull final ResourceModel model) {
        return GetDocumentRequest.builder()
                .name(model.getName())
                .documentVersion(model.getDocumentVersion())
                .build();
    }

    /**
     * When a document name is not provided, CFN will autogenerate the document name to be in the
     * format:
     * <stack-name> - <resource type> - <autogenerated ID>
     */
    private String generateName(final Map<String, String> systemTags, final String requestToken) {
        final StringBuilder identifierPrefix = new StringBuilder();

        final String stackName = MapUtils.isNotEmpty(systemTags) ?
                systemTags.get("aws:cloudformation:stack-name") + DOCUMENT_NAME_DELIMITER :
                EMPTY_STACK_NAME;
        identifierPrefix.append(stackName);

        identifierPrefix.append(DEFAULT_DOCUMENT_NAME_PREFIX);

        // This utility function will add the auto-generated ID after the prefix.
        return IdentifierUtils.generateResourceIdentifier(
                identifierPrefix.toString(),
                requestToken,
                DOCUMENT_NAME_MAX_LENGTH);
    }

    private List<Tag> translateTags(@Nullable final List<com.amazonaws.ssm.document.Tag> tags) {
        if (CollectionUtils.isEmpty(tags)) {
            return null;
        }

        return tags.stream().map(
                tag -> Tag.builder()
                        .key(tag.getKey())
                        .value(tag.getValue())
                        .build())
                .collect(Collectors.toList());
    }

    private List<AttachmentsSource> translateAttachments(@Nullable final List<com.amazonaws.ssm.document.AttachmentsSource> attachmentsSources) {
        if (CollectionUtils.isEmpty(attachmentsSources)) {
            return null;
        }

        return attachmentsSources.stream().map(
                attachmentsSource -> AttachmentsSource.builder()
                        .key(attachmentsSource.getKey())
                        .values(attachmentsSource.getValues())
                        .name(attachmentsSource.getName())
                        .build())
                .collect(Collectors.toList());
    }

    private List<DocumentRequires> translateRequires(@Nullable final List<com.amazonaws.ssm.document.DocumentRequires> requires) {
        if (CollectionUtils.isEmpty(requires)) {
            return null;
        }

        return requires.stream().map(
                documentRequires -> DocumentRequires.builder()
                        .name(documentRequires.getName())
                        .version(documentRequires.getVersion())
                        .build())
                .collect(Collectors.toList());
    }
}
